[package]
name = "rshot-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true  # This is the key line!

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "parsing"] }
