[package]
name = "rshot"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.47"
memmap2 = "0.9.8"
wayland-client = "0.31.11"
wayland-protocols = { version = "0.32.9", features = ["client", "unstable"]}
wayland-protocols-wlr = { version = "0.3.9", features = ["client"] }
